import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken
from app.config import get_settings


def _fernet() -> Fernet | None:
    key = get_settings().app_encryption_key.strip()
    if not key:
        return None
    try:
        # Preserve compatibility with all keys generated by the local releases.
        return Fernet(key.encode())
    except (TypeError, ValueError):
        # Cloud hosts normally generate an arbitrary high-entropy secret rather
        # than a Fernet-formatted key. Deriving a stable Fernet key supports both.
        derived = base64.urlsafe_b64encode(hashlib.sha256(key.encode()).digest())
        return Fernet(derived)


def encrypt(value: str | None) -> str | None:
    if value is None:
        return None
    f = _fernet()
    if not f:
        return value
    return f.encrypt(value.encode()).decode()


def decrypt(value: str | None) -> str | None:
    if value is None:
        return None
    f = _fernet()
    if not f:
        return value
    try:
        return f.decrypt(value.encode()).decode()
    except InvalidToken as exc:
        raise RuntimeError("APP_ENCRYPTION_KEY does not match the key used to encrypt stored tokens") from exc
